# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Deploy AKS'
  inputs:
    azureSubscription: 'AzureAksWorkShopSc'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'azure_deployment/azure-aks-deploy.sh'
    arguments: '$(sshPubKey)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzureCLI@2
  displayName: 'Deploy ACR'
  inputs:
    azureSubscription: 'AzureAksWorkShopSc'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'azure_deployment/azure-acr-deploy.sh'
    arguments: '$(pathRatingsAPI)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'