# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'DeployAKS'
  displayName: 'Deploy AKS'
  jobs:
  - job: 'DeployAKS'
    displayName: 'Deploy AKS'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy AKS'
      inputs:
        azureSubscription: 'AzureAksWorkShopSc'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'azure_deployment/azure-aks-deploy.sh'
        arguments: '$(sshPubKey) $(aksClusterName)'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

- stage: 'DeployACR'
  displayName: 'Deploy ACR & Build images'
  jobs:
  - job: 'DeployACR'
    displayName: 'Deploy ACR & Build images'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy ACR & Build images'
      inputs:
        azureSubscription: 'AzureAksWorkShopSc'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'azure_deployment/azure-acr-deploy.sh'
        arguments: '$(pathRatingsAPI) $(pathRatingsWeb) $(aksClusterName)'
        workingDirectory: '$(System.DefaultWorkingDirectory)'